version: '3.6'

volumes:
    mysql-data:
        driver: local

services:
    milelane:
        build:
            context: .
            dockerfile: Dockerfile.dev
        hostname: docker-local.milelane.co
        ports:
          - 80:80
        environment:
            - MILELANE_DATABASE_USERNAME=root
            - MILELANE_DATABASE_PASSWORD=
            - MILELANE_DATABASE_HOST=mysql
            - MILELANE_DATABASE=milelane
            - PORT=80
        depends_on:
            - mysql
        entrypoint:
            - dockerize
            - -timeout
            - 60s
            - -wait
            - tcp://mysql:3306
        command: ./main
    mysql:
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=milelane
            - MYSQL_USER=root
        volumes:
            - mysql-data:/var/lib/mysql
            # データベースの文字コードをutf8mb4に統一するために指定する
            - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
            # initdb.d の実行順はアルファベット順
            # https://tech.mokelab.com/infra/docker/images/mysql/initdb.html
            - ./db/create_db.sql:/docker-entrypoint-initdb.d/000_create_db.sql
            - ./db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
            - ./db/seed/seed.sql:/docker-entrypoint-initdb.d/002_seed.sql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
