version: '3.6'

volumes:
    mysql-data:
        driver: local

services:
    milelane:
        build: .
        hostname: docker-local.milelane.co
        ports:
          - 80:80
        environment:
            - MILELANE_DATABASE_USERNAME=root
            - MILELANE_DATABASE_PASSWORD=
            - MILELANE_DATABASE_HOST=milelane_mysql_1
            - MILELANE_DATABASE=milelane
            - PORT=80
        depends_on:
            - mysql
    mysql:
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - mysql-data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
