# Golang CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1
        environment:
          GO111MODULE: "on"
      - image: circleci/mysql:5.7.26
        environment: # environment variables for primary container
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: milelane
          MYSQL_USER: root
    working_directory: /go/src/github.com/whalepod/milelane
    steps:
      - run:
          name: "Wait for DB."
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - checkout
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt update
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root < db/schema.sql
            mysql -h 127.0.0.1 -u root < db/seed/seed.sql
      - run:
          name: "Create a tmp directory for artifacts which is used for codecov."
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "Execute lint."
          command: |
            GO111MODULE=off go get golang.org/x/lint/golint
            golint -set_exit_status ./...
      - run:
          name: "Execute test and get coverage report."
          command: |
            go clean -cache
            go test -cover -coverprofile=cover.out ./...
            mv cover.out /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/cover.out
